### ISSUE TITLE
How to use WiFiManager_Generic_Lite for the Adafruit Feather M0 Board ?

### ISSUE THREAD

**Issue by iKK001** [khoih-prog/WiFiManager_Generic_Lite#1]
I would like to get `WiFiManager_Generic_Lite` running on an [Adafruit Feather M0](https://www.adafruit.com/product/3061) Board. 

I tried to follow your installation and patching instructions. But I can't get it to work with this Feather M0.

Here are a couple of questions :

a) Installing the `WiFiManager_Generic_Lite` library inside Arduino IDE leads to error:  `no protocol`
(I assume I have to "Install WiFiManager_Generic_Lite only" - then it works) - but I am not sure if there are still missing libraries...)

b)  it is unclear which Arduino Libraries need to be installed next to `WiFiManager_Generic_Lite` for my [Adafruit Feather M0](https://www.adafruit.com/product/3061) Board?

![Screenshot 2021-07-03 at 16 55 43](https://user-images.githubusercontent.com/8404556/124358398-5f3f9a00-dc20-11eb-8bf9-ce9a4d886ca1.png)

c) And the third question: Having this [Adafruit Feather M0](https://www.adafruit.com/product/3061) Board in hand, which Example Code out of the list shown in the blow screenshot will work ?

![Screenshot 2021-07-03 at 16 52 47](https://user-images.githubusercontent.com/8404556/124358138-3539a800-dc1f-11eb-9e37-d859d3a022dc.png)

d) Or are there any more libraries or Patches that need to be carrried out for this [Adafruit Feather M0](https://www.adafruit.com/product/3061) Board ? If yes, what are the necessary steps ?

**Comment by iKK001** [comment]
I advanced a tiny wee bit:

The following libraries are needed on the [Adafruit Feather M0](https://www.adafruit.com/product/3061) Board:

WiFiManager_Generic_Lite
WiFiWebServer
Functional-Vlpp
DoubleResetDetector_Generic
FlashStorage_SAMD
WiFi101

With those libraries, the default Code will compile and the download to the Adafruid Feather M0 Board works.

However, now I do not see the Access Point.

What is still wrong ??

**Comment by iKK001** [comment]
Finally, using the Adafruit Feather M0, you must take care of the differnt pinout :

Please set the pins as follows - and by doing so everything works !!!!!

```
void setup()
{
  // This is the only line of code that is Feather M0 WINC1500
  // specific, the rest is the same as for the WiFi101
  WiFi.setPins(8, 7, 4, 2);

  // ... the rest of whatever was there...
}
```

**Comment by khoih-prog** [comment]
Hi @iKK001 

Glad you found out the correct way to use.

I'm late in letting you know you have to use the correct pin settings for the board.

![Selection_832](https://user-images.githubusercontent.com/57012152/124365002-3fee4000-dc13-11eb-8ad0-3e3fc8440ed8.png)

Your experience will definitely help other users.

Cheers,

**Comment by iKK001** [comment]
Dear Khoih,
  the Adafruit Feather M0 still does not work with your WiFiManager_Generic_Lite (WiFi1010) library - and I am quite desperate about it.

I did buy the more modern board "Adafruit Nano RP2040 Connect" and then your library works just fine.

But I had to realize that my existing sleep-mode and interrupt code does not 1:1 work for the RP2040. Or in other words, I have too much code that only works for my Feather M0 and not for the RP2040.

Therefore, I am extremely desperate to get your WiFiManger_Generic_Lite library up'N'running also for the Feather M0.

Again, it all works until the moment where I type in 192.168.4.1   : My browser then shows nothing at all. (i.e. with the RP2040 it worked).

Is there any way you can find some time to investigate what the Feather M0 is doing differently ? 
It must be a very small thing I am sure - but I do not have the experience to understand your code just yet.

Thank you very much for any help on this.

**Comment by khoih-prog** [comment]
You can try either

1. Nano-33-IoT, which is SAMD21-based board, using the same WiFiNINA_Generic library, and you can use the same interrupt / sleep code
2. Have a look at the [https://github.com/khoih-prog/RPI_PICO_TimerInterrupt](https://github.com/khoih-prog/https://github.com/khoih-prog/RPI_PICO_TimerInterrupt) or [MBED_RPI_PICO_TimerInterrupt](https://github.com/khoih-prog/MBED_RPI_PICO_TimerInterrupt) if you'd like to use the TimerInterrupt
3. The issue for M0 is deep inside either the board design (wiring, pin-outs, etc.) or the WiFi101 library. I reach my limit to be able to solve it without the physical board. I also don't like to spend time on the not-polular out-of-date board.  
I suggest you can post on [**Adafruit Supported Products & Projects forum**](https://forums.adafruit.com/viewforum.php?f=36&sid=a10667392ea51bb5a0514268471f9dd5) to ask for help

Sorry and good luck.

**Comment by iKK001** [comment]
Thank you very much for the ideas.

I am not interested in a TimerInterrupt but rather how to put the RP2040 Connect in DEEP SLEEP and how it can be waken up by a hardware pin interrupt. I already asked in  the Arduino Forum but no answers yet. Maybe you have an idea ?

Since battery power is very critical I'd like to have the RP2040 Connect board in sleep-mode until a hardware pin is pulled low.  The Feather M0 can do that without problems. However, for the RP2040 Connect there is no library yet that I've found to do that.

Isn't the RP2040 Connect also a SAMD21 based board and should be able to work with the same interrupt / sleep mode libraries ?? It is hard to understand why the Arduino Low Power Library does not work (https://github.com/arduino-libraries/ArduinoLowPower) - or its dependent RTCZero library as well (https://github.com/arduino-libraries/RTCZero). Do you have an idea ?

Therefore I am not sure if the Nano-33-IoT you suggest is any better. Especially since this board is not mentioned in the Arduino Low Power Library (or RTCZero) as well. So I don't think it is worth buying another board and hoping to eventually get it in DEEP SLEEP...

Did you ever put an RP2040 Connect in SLEEP Mode ?

And in general - if you are open for a customer-feedback :
As a user struggling with it since days, I think you should take out the Adadruit Feather M0 (possibly also the Feather M0 Express) completely out of your WiFiManager_Generic_Lite library documentation. Due to the fact that it simply does not work out of the box.

What is the difference between WiFiNINA_Generic_Lite library and  WiFiNINA_Generic library ? Does the first one use the second one for all non-WiFi101 boards ?  This is something you also could describe a bit better in your documentation maybe since very unclear to first use users like me. Thanks

I appreciate your answers very much. Thank you very much.

**Comment by rahulrana-XOM** [comment]
@iKK001 Did you manage to get the library working for the Adafruit Feather M0?

**Comment by iKK001** [comment]
nope - unfortunately not. I contacted the library owner. But there is not much support for this board from his side.
