### ISSUE TITLE
Config Panel does not proceed 

### ISSUE THREAD

**Issue by wiseac** [khoih-prog/WiFiManager_Generic_Lite#4]
Hello,

I am using a Teensy 4.0 with a [ESP32](https://www.adafruit.com/product/4264) module. Currently i have a hangup on...

```
Start Teensy_WiFi on TEENSY 4.0 with WiFiNINA using WiFiNINA_Generic Library
WiFiMulti_Generic v1.1.1
WiFiManager_Generic_Lite v1.8.0
[WG] Hostname=Teensy-Master-Controller


EEPROM size = 1080, start = 0
Flag read = 0xD0D01234
doubleResetDetected
ClearFlag write = 0xD0D04321
[WG] Double Reset Detected
[WG] InitEEPROM,sz=1080
[WG] EEPROMsz:1024
[WG] CCSum=0x11d0,RCSum=0x11d0
[WG] ======= Start Stored Config Data =======
[WG] Hdr=WIFI_GENERIC,SSID=SSID1,PW=password1
[WG] SSID1=SSID2,PW1=password2
[WG] BName=SAMD-Control
[WG] bg: isForcedConfigPortal = false
[WG] bg:Stay forever in CP:DRD/MRD
```

It does not proceed after this and i cant figure out why. Its detecting the module but not going any farther. (Im using the Teensy example with minor adjustments.)

Best,
W 

Using the WifiNINA manager has the same results.
```
Starting Teensy_WiFiNINA on TEENSY 4.0
WiFiMulti_Generic v1.1.1
WiFiManager_NINA_Lite v1.7.1
[WN] Hostname=Teensy-Master-Controller

EEPROM size = 1080, start = 0
Flag read = 0xD0D01234
doubleResetDetected
ClearFlag write = 0xD0D04321
[WN] Double Reset Detected
[WN] InitEEPROM,sz=1080
[WN] EEPROMsz:512
[WN] CCSum=0x11ed,RCSum=0x11ed
[WN] ======= Start Stored Config Data =======
[WN] Hdr=WIFININA,SSID=SSID1,PW=password1
[WN] SSID1=SSID2,PW1=password2
[WN] BName=Teensy-Control
[WN] bg: isForcedConfigPortal = false
[WN] bg:Stay forever in CP:DRD/MRD
```

**Comment by khoih-prog** [comment]
HI @wiseac 

I suggest that you first try using the examples of Adafruit WiFiNINA, **WiFiNINA_Generic** / WiFiNINA libraries to see if there is anything wrong with your board, firmware, core, installation, etc.

Then moving on to more complex examples of this library when everything is OK with **WiFiNINA_Generic** which is used by WiFiManager libraries.

Many users are using this [**Adafruit AirLift FeatherWing – ESP32 WiFi Co-Processor**](https://www.adafruit.com/product/4264) module successfully with Teensy 4.x. Check

1. [Teensy 4.1 - Adafruit Airlift Featherwing Co-Processor FTP Server not opening Port 21](https://forum.pjrc.com/threads/70062-Teensy-4-1-Adafruit-Airlift-Featherwing-Co-Processor-FTP-Server-not-opening-Port-21)
2. [WiFiNINA_Generic Library for WiFiNINA modules to support Teensy and more boards](https://forum.pjrc.com/threads/60245-WiFiNINA_Generic-Library-for-WiFiNINA-modules-to-support-Teensy-and-more-boards)

I'm closing the issue now as this is not a proven bug of this library. I also don't have that kind of Featherwing to test to help. Sorry.

If you have further issue, please post on [Teensy Forum](https://forum.pjrc.com) for help from many good experts there.

Good Luck,
